# Setup
title: Harry's Blog
url: https://www.harry.com/blog
baseurl: /blog

author:
  name: 'Harry Mumford-Turner'
  url: https://www.harrymt.com/


exclude: [
      "CNAME",
      "README.md"
      ]
